"""
FastAPI application for the AI dropshipping backend.

This module defines a minimal API surface that will be expanded in later
iterations.  It includes:

* A health check endpoint (`/health`) to verify that the service is
  running.
* A simple in-memory store for products as a placeholder for the
  database.
* CRUD operations on products (list and create) to illustrate the
  pattern of exposing domain entities via HTTP.

In a full implementation these handlers would interact with Supabase
via an ORM or SQL queries and perform validation, authentication and
authorization.
"""

from typing import List, Optional

from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

app = FastAPI(title="AI Dropshipping API", version="0.1.0")


class HealthResponse(BaseModel):
    status: str = Field(..., description="Status of the service, 'ok' if healthy")


@app.get("/health", response_model=HealthResponse)
async def health() -> HealthResponse:
    """Return a simple status object indicating the service is up."""
    return HealthResponse(status="ok")


class Product(BaseModel):
    id: int
    title: str
    cost_price: float
    sale_price: float
    score: Optional[float] = None


class CreateProductRequest(BaseModel):
    title: str = Field(..., description="Title or name of the product")
    cost_price: float = Field(..., ge=0, description="Cost from the supplier")
    sale_price: float = Field(..., ge=0, description="Retail price")


# In-memory store to hold products temporarily.  In a real application
# this would be replaced by database operations.
_products: List[Product] = []


@app.get("/products", response_model=List[Product])
async def list_products() -> List[Product]:
    """
    List all products currently registered in the system.

    This endpoint is a placeholder; in production it would query the
    database and support pagination.
    """
    return _products


@app.post("/products", response_model=Product, status_code=status.HTTP_201_CREATED)
async def create_product(req: CreateProductRequest) -> Product:
    """
    Create a new product.

    This is a simplified implementation that assigns sequential IDs
    starting from 1 and stores the product in memory.  In production
    the ID would be generated by the database and additional fields
    such as supplier ID, scores and statuses would be managed.
    """
    new_id = len(_products) + 1
    product = Product(id=new_id, title=req.title, cost_price=req.cost_price,
                      sale_price=req.sale_price)
    _products.append(product)
    return product
